
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 100
        parameters:
            # these must directly be a variable defined in GopherCAN
            # Listed in order of their pins in the sensor hub board side connector
            shockPosRearLeft_mm:
                ADC: ADC1_IN4
                sensor: rear_left_shock_pos
                samples_buffered: 2
            radWaterTempIn_C:
                ADC: ADC1_IN5
                sensor: temp_sensor
                samples_buffered: 2
            radWaterTempOut_C:
                ADC: ADC1_IN6
                sensor: temp_sensor
                samples_buffered: 2
            # WaterSpeedRearLeft:
            #     ADC: ADC1_IN7
            #     sensor: speed_sensor
            #     samples_buffered: 2
            # fuelPressure_psi:
            #     ADC: ADC1_IN14
            #     sensor: pressure_sensor_absolute
            #     samples_buffered: 2
            # leftAuxPressure_psi:
            #     ADC: ADC1_IN6
            #     sensor: pressure_sensor_absolute
                # samples_buffered: 2
            # leftShroudPitot_inH2O:
            #     ADC: ADC1_IN7       # pin 6 -> ADC1_IN7 is not currently working correctly
            #     sensor: differential_pressure_sensor
            #     samples_buffered: 2
            wheelSpeedRearLeft_mph:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2
            # leftFlowRate_GPerSec:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 2
            # leftFlowRateFreq_hz:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 2