
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 100
        parameters:
            # these must directly be a variable defined in GopherCAN
            # Listed in order of their pins in the sensor hub board side connector
            shockPosRearLeft_mm:
                ADC: ADC1_IN7
                sensor: rear_left_shock_pos
                samples_buffered: 2
            # radWaterTempIn_C:
            #     ADC: ADC1_IN5
            #     sensor: temp_sensor
            #     samples_buffered: 2
            # radWaterTempOut_C:
            #     ADC: ADC1_IN6
            #     sensor: temp_sensor
            #     samples_buffered: 2
            brakeTempRearLeft_C:
                ADC: ADC1_IN14
                sensor: brake_temp_sensor
                samples_buffered: 2
            wheelSpeedRearLeft_mph:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 2